sudo: false
language: php
php:
  - 7.0
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
before_install:
  - composer selfupdate
install:
  - composer install
after_script:
  - CODECLIMATE_REPO_TOKEN=705f9d8b61b3d225512def269143ead26b0d5fe50181608d7cefd218cac1b027 ./vendor/bin/test-reporter
